language: java
jdk:
  - oraclejdk11
beforeinstall:
  - sudo apt-get update
  - cd app/
  - echo "Let's start Maven Package"
  - mvn clean package
  - cd ..
  - echo "We are in root dir"
script:
  - docker-compose build
before_deploy: 
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME"  --password-stdin
deploy:
  provider: script
  script:
    docker tag docker-from-zero-mastery-java:latest danilooliveira99/docker-from-zero-mastery-java:$TRAVIS_JOB_ID;
    docker push danilooliveira99/docker-from-zero-mastery-java;
  on:
    branch: main
notifications:
   email: false
